name: Build site

on:
  push:
    branches:
      - main

env:
  CI: false

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@main

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'

    - name: npm install, build, and test
      run: |
        npm install
        npm run build

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: drop
        path: ./build

  infra:
    name: infra
    runs-on: ubuntu-latest
    needs: Build
  
    steps:

    - name: Checkout code
      uses: actions/checkout@main

    - name: Log into Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure CLI Create resource group  
      uses: Azure/cli@1.0.4
      with:
         inlineScript: az group create -n resumeRG -l 'West Europe'

    - name: Deploy Bicep file
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: 776c7557-6b68-48a7-8cae-b58457695823
        resourceGroupName: resumeRG
        template: 'Deployment/main.bicep'


  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: infra
    
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: drop
    
    - name: Azure login
      uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Upload to Azure blob storage
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
            $Conn=$(az storage account show-connection-string --name resumestrgacc --resource-group resumeRG --subscription MainSubscription)

            az group create -n resumeRG -l 'West Europe'

            az storage blob service-properties update --account-name resumestrgacc --connection-string $Conn --static-website --index-document index.html

            az storage blob delete-batch --account-name resumestrgacc --connection-string $Conn --source '$web'

            az storage blob upload-batch --account-name resumestrgacc --connection-string $Conn -d '$web' -s ./drop
